workflows:
  android-workflow:
    name: Build APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.glitchborn.ai"
      node: 16.20.0
      java: 11
    scripts:
      - npm install
      - cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk